export const GET_ITEMS = 'GET_ITEMS';

export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';
export const REFRESH_FAVOURITES_LIST='REFRESH_FAVOURITES_LIST';